version: '3.9'

services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /root/dba/postgres/data:/var/lib/postgresql/data
    env_file:
      - /root/dba/postgres/.env
    command: postgres -c password_encryption=scram-sha-256
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network

networks:
  postgres_network:
    name: postgres_network
    driver: bridge